version: 2.1

default: &default
  docker:
    - image: circleci/ruby:2.5.3
  working_directory: ~/app

commands:
  setup_bundle:
    description: "Setup bundle with cache"
    steps:
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle

      - run:
          name: Setup bundle
          command: |
            set -xe
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle clean

            # Resolve bundler version difference between Gemfile.lock and pre-installed in CI
            gem install restore_bundled_with --no-document
            restore-bundled-with

      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle

jobs:
  build:
    <<: *default

    steps:
      - checkout
      - setup_bundle
      - run: bundle exec rspec
      - run:
          name: generate_ical (dry run)
          command: |
            bundle exec rake generate_ical
            git --no-pager diff

  update_ical:
    <<: *default

    steps:
      - checkout
      - setup_bundle
      - run: .circleci/update_ical.sh

workflows:
  version: 2

  build:
    jobs:
      - build
      - update_ical:
          requires:
            - build
          filters:
            branches:
              only: master

  update_new_year:
    triggers:
      - schedule:
          cron: "0 0 1 1 *"
          filters:
            branches:
              only: master

    jobs:
      - update_ical
