version: 2.0

default: &default
  docker:
    - image: circleci/ruby:2.5.1
  working_directory: ~/app

save_bundle_cache_option: &save_bundle_cache_option
  key: v1-bundle-{{ checksum "Gemfile.lock" }}
  paths:
    - ~/app/vendor/bundle

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v1-bundle-{{ checksum "Gemfile.lock" }}
    - v1-bundle

jobs:
  build:
    <<: *default

    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: .circleci/setup.sh
      - save_cache:
          <<: *save_bundle_cache_option
      - run: bundle exec rspec

workflows:
  version: 2

  build:
    jobs:
      - build
