version: 2.1

orbs:
  sue445-bundle-install: sue445/bundle-install@0.1.0

default: &default
  docker:
    - image: circleci/ruby:2.5.3
  working_directory: ~/app

jobs:
  build:
    <<: *default

    steps:
      - checkout
      - sue445-bundle-install/bundle-install
      - run: bundle exec rspec
      - run:
          name: generate_ical (dry run)
          command: |
            bundle exec rake generate_ical
            git --no-pager diff

  update_ical:
    <<: *default

    steps:
      - checkout
      - sue445-bundle-install/bundle-install
      - run: .circleci/update_ical.sh

workflows:
  version: 2

  build:
    jobs:
      - build
      - update_ical:
          requires:
            - build
          filters:
            branches:
              only: master

  update_new_year:
    triggers:
      - schedule:
          cron: "0 0 1 1 *"
          filters:
            branches:
              only: master

    jobs:
      - update_ical
