title: "キラッとプリ☆チャン"
characters:
  - name:     "桃山みらい"
    birthday: "7/12"
  - name:     "萌黄えも"
    birthday: "9/9"
  - name:     "青葉りんか"
    birthday: "1/25"
  - name:     "赤城あんな"
    birthday: "7/6"
  - name:     "緑川さら"
    birthday: "6/9"
